repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run Unit Tests
        entry: python -m unittest discover -s tests -p '*_test.py'
        language: system
        always_run: true
        pass_filenames: false
